# Generated by Django 4.1.1 on 2022-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_venue_email_address_alter_venue_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Venue owner'),
        ),
    ]
